version: "3"
services:
  app:
    build:
      context: .
    container_name: flaskd3-api
    hostname: flaskd3-api
    environment:
      PYTHONPATH: /usr/local/app
    depends_on:
      - mysql
    volumes:
      - ./flaskd3:/usr/local/app/flaskd3
      - ./sql:/usr/local/app/sql
      - ./tests:/usr/local/app/tests
      - ./app.py:/usr/local/app/app.py
      - ./Makefile:/usr/local/app/Makefile
      - ./Pipfile:/usr/local/app/Pipfile
      - ./Pipfile.lock:/usr/local/app/Pipfile.lock
    env_file: .env
    user: "${UID}:${GID}"
    command: tail -f /dev/null

  mysql:
    image: mysql:5.7
    container_name: flaskd3-db
    hostname: flaskd3-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: flaskd3
      MYSQL_USER: flaskd3
      MYSQL_PASSWORD: flaskd3
      MYSQL_DATABASE: flaskd3
    command: --sql_mode="no_engine_substitution"

networks:
  default:
    external:
      name: flaskd3